spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: aea56483c6c9f1d58d17
            client-secret: aecbe88b2157d103b1c03ed1b6341e7be1f160a2
            client-name: "Client for user scope"
            provider: "github"
            scope:
              - user:email
              - read:user
          resource:
              user-info-uri: https://api.github.com/user